name: Docker

on:
  push:
    tags:
      - 'v*.*.*'
      - 'b*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ${{ fromJSON( startsWith( github.ref_name, 'v' ) && '["server", "server-beta"]' || '["server-beta"]' ) }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.environment }}
          flavor: latest=true
          tags: type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
